spring:
  application:
    name: ncapas-parcial-ii

  datasource:
    url: jdbc:postgresql://localhost:5432/magic_wand
    username: dev_pilito
    password: root123

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect